-- ==========================================================================
-- ZO Y LA - SUPABASE / POSTGRESQL SCHEMA
-- ==========================================================================

-- 1. Tabla de Servicios
CREATE TABLE IF NOT EXISTS services (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    duration INT NOT NULL DEFAULT 60,
    price DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    icon VARCHAR(50) DEFAULT 'brain',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de Clientes
CREATE TABLE IF NOT EXISTS clients (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(50),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla de Notas del Cliente
CREATE TABLE IF NOT EXISTS client_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(50) NOT NULL,
    note_date TIMESTAMPTZ NOT NULL,
    note_text TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
);

-- 4. Tabla de Citas / Reservas
CREATE TABLE IF NOT EXISTS appointments (
    id VARCHAR(50) PRIMARY KEY,
    client_id VARCHAR(50),
    client_name VARCHAR(255) NOT NULL,
    client_email VARCHAR(255) NOT NULL,
    client_phone VARCHAR(50),
    service_id VARCHAR(50),
    service_name VARCHAR(255) NOT NULL,
    appointment_date DATE NOT NULL,
    appointment_time VARCHAR(20) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'confirmed', -- pending, confirmed, completed, cancelled
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
    FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE SET NULL
);

-- 5. Tabla de Usuarios (Administración)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'admin',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Deshabilitar RLS temporalmente o permitir lecturas/escrituras para clientes anónimos durante pruebas en Supabase
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public full access to services" ON services FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to clients" ON clients FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to client_notes" ON client_notes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public full access to appointments" ON appointments FOR ALL USING (true) WITH CHECK (true);

-- Datos Iniciales por Defecto
INSERT INTO services (id, name, description, duration, price, icon) VALUES
('serv-1', 'Terapia Individual Gestalt', 'Espacio de autodescubrimiento y presencia para procesar emociones, resolver bloqueos existenciales y reconciliarte con tu presente.', 60, 60.00, 'brain'),
('serv-2', 'Coaching Ontológico', 'Acompañamiento enfocado a la acción, redefiniendo tus metas personales y profesionales. Ideal para transiciones de vida.', 60, 70.00, 'compass'),
('serv-3', 'Sesión de Mindfulness y Relajación', 'Prácticas guiadas individuales para reducir el estrés, arraigar la mente en el cuerpo y cultivar la calma interior.', 45, 45.00, 'sparkles')
ON CONFLICT (id) DO NOTHING;

INSERT INTO clients (id, name, email, phone) VALUES
('cli-1', 'Ana García', 'ana.garcia@gmail.com', '+34 611 222 333'),
('cli-2', 'Carlos Mendoza', 'carlos.mendoza@outlook.com', '+34 622 333 444'),
('cli-3', 'Laura Martínez', 'laura.mtz@yahoo.com', '+34 633 444 555')
ON CONFLICT (id) DO NOTHING;

INSERT INTO client_notes (client_id, note_date, note_text) VALUES
('cli-1', '2026-07-01 10:00:00+00', 'Iniciamos proceso Gestalt. Presenta ansiedad por transición laboral. Trabajamos respiración y arraigo.'),
('cli-1', '2026-07-08 10:00:00+00', 'Segunda sesión. Exploramos la "silla vacía" para resolver conflicto pendiente con su antiguo jefe. Reporta mejor descanso.'),
('cli-2', '2026-07-05 12:00:00+00', 'Sesión de coaching de vida. Busca definir objetivos de cara a emprender. Identificamos creencias limitantes sobre el dinero.')
ON CONFLICT DO NOTHING;

INSERT INTO appointments (id, client_id, client_name, client_email, client_phone, service_id, service_name, appointment_date, appointment_time, price, status, notes) VALUES
('app-1', 'cli-1', 'Ana García', 'ana.garcia@gmail.com', '+34 611 222 333', 'serv-1', 'Terapia Individual Gestalt', '2026-07-15', '10:00', 60.00, 'confirmed', 'Continuación de la sesión anterior.'),
('app-2', 'cli-2', 'Carlos Mendoza', 'carlos.mendoza@outlook.com', '+34 622 333 444', 'serv-2', 'Coaching Ontológico', '2026-07-15', '12:00', 70.00, 'pending', 'Primera sesión sobre metas de emprendimiento.'),
('app-3', 'cli-3', 'Laura Martínez', 'laura.mtz@yahoo.com', '+34 633 444 555', 'serv-3', 'Sesión de Mindfulness', '2026-07-16', '16:00', 45.00, 'confirmed', '')
ON CONFLICT (id) DO NOTHING;
